### ISSUE TITLE
Remove extra files from repo please. 

### ISSUE THREAD

**Issue by faisalnazik** [javitocor/Blog-Django#1]
I was cloning it and its status was just 6 %  with  43.15 MiB | 505.00 KiB/s. Too much size of this repo. So please remove extra files if you can like media files and static files. Thanks! 
![image](https://user-images.githubusercontent.com/68164877/134374973-bcd758f0-c412-4aba-a463-a3da4c26bc23.png)

**Comment by javitocor** [comment]
Done! you should have no problems downloading it now!
